openapi: 3.0.3
info:
  title: OpenAPI schema for BlackBox Exporter template .
components:
  schemas:
    variables:
      type: object
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: Namespace where BlackBox Exporter will be installed.
          default: prometheus-system
          x-walrus-ui:
            group: Basic
            order: 1
        helm_release_name:
          title: Helm Release Name
          type: string
          description: Name for the BlackBox Exporter Helm release.
          default: prometheus-blackbox-exporter
          x-walrus-ui:
            group: Basic
            order: 2
        helm_release_version:
          title: Helm Release Version
          type: string
          description: Version of the BlackBox Exporter Helm chart.
          default: 8.17.0
          x-walrus-ui:
            group: Basic
            order: 3
        service_monitor:
          title: Service Monitor
          type: boolean
          description: Enable or disable serviceMonitor.
          default: true
          x-walrus-ui:
            group: Basic
            order: 4
        pod_monitoring:
          title: Pod Monitoring
          type: boolean
          description: Enable or disable podMonitoring.
          default: true
          x-walrus-ui:
            group: Basic
            order: 5
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for the BlackBox Exporter Helm
            release.
          default:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 50Mi
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
      x-walrus-ui:
        groupOrder:
        - Basic
