openapi: 3.0.3
info:
  title: OpenAPI schema for BlackBox Exporter template .
components:
  schemas:
    variables:
      type: object
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: Namespace where BlackBox Exporter will be installed.
          default: prometheus-system
          x-walrus-ui:
            group: Basic
            order: 1
        helm_release_name:
          title: Helm Release Name
          type: string
          description: Name for the BlackBox Exporter Helm release.
          default: prometheus-blackbox-exporter
          x-walrus-ui:
            group: Basic
            order: 2
        helm_release_version:
          title: Helm Release Version
          type: string
          description: Version of the BlackBox Exporter Helm chart.
          default: 8.17.0
          x-walrus-ui:
            group: Basic
            order: 3
        service_monitor_enabled:
          title: Service Monitor Enabled
          type: boolean
          description: Enable or disable serviceMonitor.
          default: true
          x-walrus-ui:
            group: Basic
            order: 4
        pod_monitoring_enabled:
          title: Pod Monitoring Enabled
          type: boolean
          description: Enable or disable podMonitoring.
          default: true
          x-walrus-ui:
            group: Basic
            order: 5
      x-walrus-ui:
        groupOrder:
        - Basic
